### ISSUE TITLE
npm ERR! code ELIFECYCLE

### ISSUE THREAD

**Issue by theotix** [tec27/seatcamp#11]
Hi,
I tried to update my instance of meatspace on my own server, but at the "npm start" state, there is apparently some problems. Do you have an idea of what it is ?

npm ERR! seatcamp@1.0.0 start: `node index.js`
npm ERR! Exit status 8
npm ERR!
npm ERR! Failed at the seatcamp@1.0.0 start script.
npm ERR! This is most likely a problem with the seatcamp package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node index.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls seatcamp
npm ERR! There is likely additional logging output above.
npm ERR! System Linux 3.2.0-4-amd64
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! cwd /var/www/seatcamp
npm ERR! node -v v0.10.40
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /var/www/seatcamp/npm-debug.log
npm ERR! not ok code 0

The server is on Debian Weezy

**Comment by theotix** [comment]
Me again,
Seems to be a problem with the babel module :
/var/www/seatcamp/server.js:67
const userIdKey = _confJson2['default'].idKey;
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at normalLoader (/var/www/seatcamp/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:199:5)
    at Object.require.extensions.(anonymous function) [as .js] (/var/www/seatcamp/node_modules/babel/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/www/seatcamp/index.js:12:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)

**Comment by tec27** [comment]
Make sure your server has a version of Node >= 4.0.0

**Comment by theotix** [comment]
Oh that why, after upgrade and a few module installed, it's works, thanks!

**Comment by tec27** [comment]
Great!
